# Generated by Django 6.0 on 2026-01-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='venue',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft-disable venue without deleting history'),
        ),
        migrations.AddField(
            model_name='venue',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='Flag for librarian review'),
        ),
    ]
