# Generated by Django 6.0 on 2025-12-23 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0004_rename_concertroletype_personroletype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('year_composed', models.CharField(blank=True, help_text="Year or range (free text, e.g.'1936', 'c. 1900')", max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MusicPersonRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='music.music')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_roles', to='people.person')),
                ('role_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='music_roles', to='people.personroletype')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('music', 'person', 'role_type')},
            },
        ),
    ]
