# Generated by Django 6.0 on 2025-12-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='location_drawer',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Physical drawer number', null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='location_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Folder number within the drawer', null=True),
        ),
    ]
