# Generated by Django 6.0 on 2025-12-25 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_music_location_drawer_music_location_number'),
        ('people', '0006_person_external_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MusicPersonRole',
            new_name='MusicRole',
        ),
    ]
