# Generated by Django 6.0 on 2025-12-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_rename_musicpersonrole_musicrole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name_plural': 'Music'},
        ),
        migrations.AddField(
            model_name='musicrole',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft-disable role types without breaking history'),
        ),
    ]
