# Generated by Django 6.0 on 2025-12-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_music_options_musicrole_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='status',
            field=models.CharField(choices=[('OWN', 'Owned'), ('BOR', 'Borrowed'), ('LOAN', 'On Loan'), ('ARC', 'Archived / Removed')], db_index=True, default='OWN', max_length=4),
        ),
    ]
