# Generated by Django 6.0 on 2025-12-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_music_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ('title',), 'verbose_name': 'Music', 'verbose_name_plural': 'Music'},
        ),
        migrations.AddField(
            model_name='music',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('E', 'Easy'), ('ME', 'Moderately Easy'), ('M', 'Moderate'), ('MD', 'Moderately Difficult'), ('D', 'Difficult')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='music',
            name='duration',
            field=models.DurationField(blank=True, help_text='Enter duration as mm:ss', null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='score_missing',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='music',
            name='status',
            field=models.CharField(choices=[('OWN', 'Owned'), ('BOR', 'Borrowed'), ('LOAN', 'On Loan'), ('RENT', 'Rental'), ('ARC', 'Archived / Removed')], db_index=True, default='OWN', max_length=4),
        ),
    ]
