# Generated by Django 6.0 on 2026-01-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_music_options_music_difficulty_music_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='status',
        ),
    ]
