# Generated by Django 6.0 on 2026-01-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_remove_music_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, help_text='Is this piece part of our active library collection?'),
        ),
        migrations.AddField(
            model_name='music',
            name='needs_review',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='music',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
