# Generated by Django 6.0 on 2026-01-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
        ('music', '0008_music_created_at_music_is_active_music_needs_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='music', to='genres.genre'),
        ),
    ]
