# Generated by Django 6.0 on 2026-01-09 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_music_genres'),
        ('organizations', '0003_delete_musicorganizationlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicOrganizationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, help_text='When this relationship began', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When this relationship ended', null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_links', to='music.music')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_links', to='organizations.organization')),
                ('role_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='music_links', to='organizations.organizationroletype')),
            ],
            options={
                'ordering': ['role_type__name', 'start_date'],
                'unique_together': {('music', 'organization', 'role_type', 'start_date')},
            },
        ),
    ]
