# Generated by Django 6.0 on 2026-01-04 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0007_remove_music_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('contact_person', models.CharField(max_length=100, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft-disable organization without deleting history')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationRoleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable identifier (e.g. LENDER, BORROWER, RENTAL_VENDOR, PUBLISHER)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human-readable name of the organization role (e.g. Publisher)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Organization Role Type',
                'verbose_name_plural': 'Organization Role Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organizations.organization')),
                ('role_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_roles', to='organizations.organizationroletype')),
            ],
            options={
                'unique_together': {('organization', 'role_type')},
            },
        ),
        migrations.CreateModel(
            name='MusicOrganizationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-disable organization without deleting history')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_links', to='music.music')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_links', to='organizations.organization')),
                ('role_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='music_links', to='organizations.organizationroletype')),
            ],
            options={
                'ordering': ['role_type__name'],
                'unique_together': {('music', 'organization', 'role_type')},
            },
        ),
    ]
