# Generated by Django 6.0 on 2026-01-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_music_created_at_music_is_active_music_needs_review_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [

        migrations.AddField(
            model_name='musicorganizationlink',
            name='start_date',
            field=models.DateField(blank=True, help_text='When this relationship began', null=True),
        ),
        migrations.AddField(
            model_name='musicorganizationlink',
            name='end_date',
            field=models.DateField(blank=True, help_text='When this relationship ended', null=True),
        ),

        migrations.RemoveField(
            model_name='musicorganizationlink',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='organization',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterModelOptions(
            name='musicorganizationlink',
            options={'ordering': ['role_type__name', 'start_date']},
        ),
        migrations.AlterUniqueTogether(
            name='musicorganizationlink',
            unique_together={('music', 'organization', 'role_type', 'start_date')},
        ),
    ]
