# Generated by Django 6.0 on 2026-01-09 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_musicorganizationlink_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MusicOrganizationLink',
        ),
    ]
