# Generated by Django 6.0 on 2026-01-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_delete_musicorganizationlink'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE organizations_organization "
                        "ADD COLUMN IF NOT EXISTS needs_review BOOLEAN NOT NULL DEFAULT FALSE"
                    ),
                    reverse_sql=(
                        "ALTER TABLE organizations_organization "
                        "DROP COLUMN IF EXISTS needs_review"
                    ),
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='organization',
                    name='needs_review',
                    field=models.BooleanField(default=False, help_text='Flag for librarian review'),
                ),
            ],
        ),
    ]
