# Generated by Django 6.0 on 2025-12-23 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0003_rename_roletype_concertroletype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('poster', models.ImageField(blank=True, upload_to='posters/')),
                ('description', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConcertRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='concerts.concert')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concert_roles', to='people.person')),
                ('role_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concert_roles', to='people.concertroletype')),
            ],
            options={
                'ordering': ['display_order'],
                'unique_together': {('concert', 'person', 'role_type')},
            },
        ),
    ]
