# Generated by Django 6.0 on 2025-12-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_concert_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concertrole',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
