# Generated by Django 6.0 on 2025-12-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0003_alter_concertrole_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='concertrole',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft-disable roles without breaking history'),
        ),
    ]
