# Generated by Django 6.0 on 2025-12-26 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0004_concertrole_is_active'),
        ('music', '0004_alter_music_options_musicrole_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_order', models.PositiveIntegerField(help_text='Order of performance in the concert program')),
                ('notes', models.TextField(blank=True, help_text='Optional program-specific notes (movements, excerpts, etc.)')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_items', to='concerts.concert')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_appearances', to='music.music')),
            ],
            options={
                'ordering': ['program_order'],
                'constraints': [models.UniqueConstraint(fields=('concert', 'program_order'), name='uniq_program_order_per_concert')],
            },
        ),
    ]
