# Generated by Django 6.0 on 2026-01-20 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0005_concertprogram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='concert',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='public/posters/concerts/%Y/'),
        ),
        migrations.CreateModel(
            name='ConcertAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional override (defaults to piece title)', max_length=200)),
                ('audio_file', models.FileField(upload_to='restricted/audio/concerts/%Y/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('program_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='concerts.concertprogram')),
            ],
            options={
                'ordering': ['program_entry__concert__date', 'program_entry__program_order', 'id'],
            },
        ),
    ]
