# Generated by Django 6.0 on 2025-12-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(blank=True, help_text='Professional name, include honorific and middle initial, if needed', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Stable machine-readable identifier (e.g. CONDUCTOR)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human-readable name (e.g. Conductor)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Soft-disable role types without breaking history')),
            ],
        ),
    ]
