# Generated by Django 6.0 on 2025-12-22 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
                ('role_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.roletype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('person', 'role_type', 'start_date'), name='unique_person_role_start')],
            },
        ),
    ]
