# Generated by Django 6.0 on 2025-12-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_personrole'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoleType',
            new_name='ConcertRoleType',
        ),
        migrations.RemoveConstraint(
            model_name='personrole',
            name='unique_person_role_start',
        ),
        migrations.AddField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('IND', 'Individual'), ('ENS', 'Ensemble')], default='IND', max_length=3),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PersonRole',
        ),
    ]
