# Generated by Django 6.0 on 2025-12-23 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_concert_venue'),
        # ('music', '0001_initial'),
        ('people', '0003_rename_roletype_concertroletype_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConcertRoleType',
            new_name='PersonRoleType',
        ),
        migrations.AlterModelOptions(
            name='personroletype',
            options={'ordering': ['name']},
        ),
    ]
