# Generated by Django 6.0 on 2025-12-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_alter_person_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='external_key',
            field=models.CharField(blank=True, help_text='Temporary migration key (person_key from Phase 3)', max_length=20, null=True, unique=True),
        ),
    ]
