# Generated by Django 6.0 on 2025-12-25 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_person_external_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='external_key',
        ),
    ]
