# Generated by Django 6.0 on 2025-12-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_remove_person_external_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='personroletype',
            name='scope',
            field=models.CharField(blank=True, choices=[('concert', 'Concert'), ('music', 'Music'), ('both', 'Both')], help_text='Where this role is applicable.', max_length=10, null=True),
        ),
    ]
