# Generated by Django 6.0 on 2025-12-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_personroletype_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personroletype',
            name='scope',
            field=models.CharField(choices=[('concert', 'Concert'), ('music', 'Music'), ('both', 'Both')], help_text='Where this role is applicable.', max_length=10),
        ),
    ]
