# Generated by Django 6.0 on 2025-12-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_alter_personroletype_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='personroletype',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
    ]
