# Generated by Django 6.0 on 2025-12-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_personroletype_needs_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personroletype',
            name='needs_review',
        ),
        migrations.AddField(
            model_name='person',
            name='needs_review',
            field=models.BooleanField(default=False),
        ),
    ]
