# Generated by Django 6.0 on 2026-01-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_remove_personroletype_needs_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personroletype',
            name='display_order',
            field=models.PositiveIntegerField(default=100, help_text='Lower numbers appear earlier in lists.'),
        ),
    ]
