# Generated by Django 6.0 on 2026-01-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_personroletype_display_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=models.CharField(blank=True, choices=[('IND', 'Individual'), ('ENS', 'Ensemble')], max_length=3, null=True),
        ),
    ]
